services:
  front:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hackathon-front
    ports:
      - "3000:3000"
    command: npm run dev
    restart: always
    networks:
      - home_network
networks:
  home_network:
    external: true